# Generated by Django 2.0.4 on 2018-04-04 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ValuesEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value_b', models.DecimalField(decimal_places=2, max_digits=5)),
                ('entry_date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='valuesentry',
            unique_together={('site', 'entry_date')},
        ),
    ]
